Traceback (most recent call last):
  File "/home/hirshb/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/hirshb/.local/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/hirshb/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/hirshb/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/hirshb/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/hirshb/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
import altair as alt
import pandas as pd

m = 1.0
q0 = 1.0
w0 = 0.1

t = np.linspace( 0, 2 * np.pi / w0, 100 )

qt = q0 * np.cos( w0 * t )
pt = - m * w0 * q0 * np.sin( w0 * t )

#plt.figure(dpi=600)
#plt.xlabel(r'$q$')
#plt.ylabel(r'$p$')
#plt.scatter( qt, pt )

data = np.array([qt,pt])
data = data.T

data = pd.DataFrame(data, columns=['qt','pt'])

alt.Chart(data=data).mark_point().encode(
    x=alt.X("qt", title="q", scale=alt.Scale(domain=[-1.1, 1.1])),
    y=alt.Y("pt", title="p", scale=alt.Scale(domain=[-0.115, 0.115])),
    tooltip=('qt','pt')
).interactive().configure_point(
    size=200,
    filled=True
).configure_axis(
    labelFontSize=20,
    titleFontSize=20,
    labelFont="Roboto",
    titleFont="Roboto",
    titleFontStyle="italic",
    titleFontWeight="normal"
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01maltair[39;00m [38;5;28;01mas[39;00m [38;5;21;01malt[39;00m

[0;31mModuleNotFoundError[0m: No module named 'numpy'

